spring.application.name=ArtisanConnectBackend

## PostgreSQL
spring.datasource.url=jdbc:postgresql://192.168.56.103:5432/default_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.sql.init.data-locations=classpath:sql/data.sql
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# create and drop table, good for testing, production set to none or comment it
spring.jpa.hibernate.ddl-auto=create-drop